server:
  port: 8000

spring:
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #修改自己的teslamate数据库连接信息
    url: jdbc:postgresql://127.0.0.1:5432/teslamate
    username: teslamate
    password: teslamate

    driverClassName: org.postgresql.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出SQL日志（调试用）

#日志配置
logging:
  level:
    root: info
    cn.doveshelly.admin: debug

sys:
  config:
    #电池容量，我是标续，目前容量还剩95%，就是60*0.95
    batteryCapacity: 57.0
    #每度电话费金额，单位：元
    costPerKwh: 0.9
    #定义快充的功率阈值 (kW)。大于 22kW 通常被认为是直流快充。
    fastChargePowerThresholdKw: 22.0
    #标定百公里能耗，单位kWh/100km，用来估算能耗。我的是充满417公里，就用57.0/417*100=13.67
    ratedConsumptionKwh: 13.67

    #小程序appId
    appId:
    #小程序appSecret
    appSecret:
    #小程序自己的openId，需要本地运行后台服务，打开小程序请求登录接口，查看日志获取，用于登录
    openId:
    #前后端接口签名认证，前后端保持一致即可，自定义
    signSecret: 1234qwerasdfzxcv1234awerasdfzxc
    #根据经纬度查询具体位置，https://lbsyun.baidu.com/apiconsole/key，自己注册登录开通服务，每天300次逆地理编码调用限制
    baiduKey:
    #用于推送行程通知到钉钉，具体百度了解如何使用钉钉webhook机器人
    webhookToken:

#是否开启行程推送
alert:
  enabled: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
    # token 名称（同时也是 cookie 名称）
    token-name: satoken
    # token 有效期（单位：秒） 默认30天，-1 代表永久有效
    timeout: 2592000
    # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
    active-timeout: -1
    # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
    is-share: false
    # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
    token-style: uuid
    # 是否输出操作日志
    is-log: true





